   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   ;; Axions and methods used to modeling anchored-instruction              ;;
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   
   (:method (createLDAnchoredInstructionCLScenario ?goals ?groups)
      ()
      ((createLDAnchoredInstructionCLScenario! ?goals ?groups)))
   
   ;; mandatory (auxiliary)
   (:method (createLDAnchoredInstructionCLScenario! ?goals ?groups)
      ((assign ?id (call GetUUID play)))
      ((!startLDElement play ((identifier ?id))
                        ((AnchoredInstruction CLScenario) ?id ?goals ?groups))
       (!!changeCLGrouping ())
       (createLDTitle (AnchoredInstruction CLScenario) ?goals)
       (createAnchoredInstructionCLScenario ?goals ?groups)
       (!endLDElement play ?id)
       (createLDILEventConditions ?groups)
       ))
   
   ;; fall-back (fundamental)
   (:method (createLDAnchoredInstructionCLScenario ((?c ?il) (?c ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?c Fundamental)
       (or (equivalent (associative accretion) ?il)
           (equivalent (explanatory tuning) ?il)
           (equivalent (associative restructuring) ?il)
           (equivalent (associative tuning) ?il))
       (or (equivalent (any accretion) ?hl)
           (equivalent (any tuning) ?hl))
       ;; get goals
       (getCurrentLearningResourceType ?types)
       (getLearnerPropertyQuery ?tmpq1 ?c ?instructors)
       (buildPropertyQuery ?q1 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?il) . ?tmpq1))
       (getOrBuildReadyAux ?iaux ?q1 ?instructors)
       (getGoalFromAuxiliary ?igoal ?iaux ?c ?il)
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hl) . ?tmpq2))
       (getOrBuildReadyAux ?haux ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoal ?haux ?c ?hl)
       (assign ?id (call GetUUID play)))
      ((!startLDElement play ((identifier ?id))
               ((AnchoredInstruction CLScenario) ?id (?igoal ?hgoal) (?instructors ?holders)))
       (!!changeCLGrouping ())
       (!!changeFundCompetency ?c)
       (createLDTitle (AnchoredInstruction CLScenario) (?igoal ?hgoal))
       (createAnchoredInstructionCLScenario (?igoal ?hgoal) (?instructors ?holders))
       (!endLDElement play ?id)
       (createLDILEventConditions ?groups)
       ))
   
   ;; Method to create clscenario
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   (:method (createAnchoredInstructionCLScenario ?goals ?groups)
      ()
      ((createAnchoredInstructionCLScenario! ?goals ?groups)))
   
   ;; holders - s(x,0) : s(x, 1) -> |s(x,2)
   ;; instructors - s(2,1) : s(2,2),s(3,1) -> |s(3,2)
   (:method (createAnchoredInstructionCLScenario! ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?ic Auxiliary)
       (equivalent (associative tuning) ?il)
       (hasKnowledgeType ?hc Auxiliary)
       (equivalent (any tuning) ?hl)
       ;; get fund competency
       (getElement ?e ((class CurrentLDElement)))
       (getPropertyValue ?c ?e hasFundCompetency)
       (getCurrentLearningResourceType ?types)
       ;; get goals
       (getLearnerPropertyQuery ?tmpq1 ?c ?instructors)
       (assignIterator ?ils2k2s3k1 (s2k2 s3k1))
       (buildPropertyQuery ?q1 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?ils2k2s3k1) . ?tmpq1))
       (getOrBuildReadyAux ?iauxs2k2s3k1 ?q1 ?instructors)
       (getGoalFromAuxiliary ?igoals2k2s3k1 ?iauxs2k2s3k1 ?c ?ils2k2s3k1)
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (getPropertyValue ?sl ?hl hasSkillLevel)
       (getLevel ?hlslk1 (?sl accretion))
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hlslk1) . ?tmpq2))
       (getOrBuildReadyAux ?hauxslk1 ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoalslk1 ?hauxslk1 ?c ?hlslk1))
      ((createLDAnchoredInstructionPhase (?igoals2k2s3k1 ?hgoalslk1) (?instructors ?holders))
       (createLDAnchoredInstructionPhase ((?ic ?il) (?hc ?hl)) (?instructors ?holders))))
   
   ;; holders - s(x,0) : s(x, 1) -> |s(x,2)
   ;; instructors - s(2,1) : |s(2,2),|s(3,1) -> s(3,2)
   (:method (createAnchoredInstructionCLScenario! ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?ic Auxiliary)
       (or (equivalent (explanatory tuning) ?il)
           (equivalent (associative accretion) ?il))
       (hasKnowledgeType ?hc Auxiliary)
       (equivalent (any tuning) ?hl)
       ;; get fund competency
       (getElement ?e ((class CurrentLDElement)))
       (getPropertyValue ?c ?e hasFundCompetency)
       (getCurrentLearningResourceType ?types)
       ;; get goals
       (getLearnerPropertyQuery ?tmpq1 ?c ?instructors)
       (getLevel ?ils3k2 (associative tuning))
       (buildPropertyQuery ?q1 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?ils3k2) . ?tmpq1))
       (getOrBuildReadyAux ?iauxs3k2 ?q1 ?instructors)
       (getGoalFromAuxiliary ?igoals3k2 ?iauxs3k2 ?c ?ils3k2)
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (getPropertyValue ?sl ?hl hasSkillLevel)
       (getLevel ?hlslk1 (?sl accretion))
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hlslk1) . ?tmpq2))
       (getOrBuildReadyAux ?hauxslk1 ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoalslk1 ?hauxslk1 ?c ?hlslk1))
      ((createLDAnchoredInstructionPhase ((?ic ?il) ?hgoalslk1) (?instructors ?holders))
       (createLDAnchoredInstructionPhase (?igoals3k2 (?hc ?hl)) (?instructors ?holders))))

   ;; holders - s(x,0) : |s(x, 1) -> s(x,2)
   ;; instructors - s(2,1) : s(2,2),s(3,1) -> |s(3,2)
   (:method (createAnchoredInstructionCLScenario! ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?ic Auxiliary)
       (equivalent (associative tuning) ?il)
       (hasKnowledgeType ?hc Auxiliary)
       (equivalent (any accretion) ?hl)
       ;; get fund competency
       (getElement ?e ((class CurrentLDElement)))
       (getPropertyValue ?c ?e hasFundCompetency)
       (getCurrentLearningResourceType ?types)
       ;; get goals
       (getLearnerPropertyQuery ?tmpq1 ?c ?instructors)
       (assignIterator ?ils2k2s3k1 (s2k2 s3k1))
       (buildPropertyQuery ?q1 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?ils2k2s3k1) . ?tmpq1))
       (getOrBuildReadyAux ?iauxs2k2s3k1 ?q1 ?instructors)
       (getGoalFromAuxiliary ?igoals2k2s3k1 ?iauxs2k2s3k1 ?c ?ils2k2s3k1)
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (getPropertyValue ?sl ?hl hasSkillLevel)
       (getLevel ?hlslk2 (?sl tuning))
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hlslk2) . ?tmpq2))
       (getOrBuildReadyAux ?hauxslk2 ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoalslk2 ?hauxslk2 ?c ?hlslk2))
      ((createLDAnchoredInstructionPhase (?igoals2k2s3k1 (?hc ?hl)) (?instructors ?holders))
       (createLDAnchoredInstructionPhase ((?ic ?il) ?hgoalslk2) (?instructors ?holders))))
   
   ;; holders - s(x,0) : |s(x, 1) -> s(x,2)
   ;; instructors - s(2,1) : |s(2,2),|s(3,1) -> s(3,2)
   (:method (createAnchoredInstructionCLScenario! ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?ic Auxiliary)
       (or (equivalent (explanatory tuning) ?il)
           (equivalent (associative accretion) ?il))
       (hasKnowledgeType ?hc Auxiliary)
       (equivalent (any accretion) ?hl)
       ;; get fund competency
       (getElement ?e ((class CurrentLDElement)))
       (getPropertyValue ?c ?e hasFundCompetency)
       (getCurrentLearningResourceType ?types)
       ;; get goals
       (getLearnerPropertyQuery ?tmpq1 ?c ?instructors)
       (getLevel ?ils3k2 (associative tuning))
       (buildPropertyQuery ?q1 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?ils3k2) . ?tmpq1))
       (getOrBuildReadyAux ?iauxs3k2 ?q1 ?instructors)
       (getGoalFromAuxiliary ?igoals3k2 ?iauxs3k2 ?c ?ils3k2)
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (getPropertyValue ?sl ?hl hasSkillLevel)
       (getLevel ?hlslk2 (?sl tuning))
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hlslk2) . ?tmpq2))
       (getOrBuildReadyAux ?hauxslk2 ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoalslk2 ?hauxslk2 ?c ?hlslk2))
      ((createLDAnchoredInstructionPhase ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
       (createLDAnchoredInstructionPhase (?igoals3k2 ?hgoalslk2) (?instructors ?holders))))
   
   ;; holders - s(x,0) : s(x, 1) -> |s(x,2)
   ;; instructors - s(2,3) : s(2,3) -> |s(3,3)
   (:method (createAnchoredInstructionCLScenario! ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?ic Auxiliary)
       (equivalent (associative restructuring) ?il)
       (hasKnowledgeType ?hc Auxiliary)
       (equivalent (any tuning) ?hl)
       ;; get fund competency
       (getElement ?e ((class CurrentLDElement)))
       (getPropertyValue ?c ?e hasFundCompetency)
       (getCurrentLearningResourceType ?types)
       ;; get goals
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (getPropertyValue ?sl ?hl hasSkillLevel)
       (getLevel ?hlslk1 (?sl accretion))
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hlslk1) . ?tmpq2))
       (getOrBuildReadyAux ?hauxslk1 ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoalslk1 ?hauxslk1 ?c ?hlslk1))
      ((createLDAnchoredInstructionPhase ((?ic ?il) ?hgoalslk1) (?instructors ?holders))
       (createLDAnchoredInstructionPhase ((?ic ?il) (?hc ?hl)) (?instructors ?holders))))
    
   ;; holders - s(x,0) : |s(x, 1) -> s(x,2)
   ;; instructors - s(2,3) : s(2,3) -> |s(3,3)
   (:method (createAnchoredInstructionCLScenario! ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
      ((hasKnowledgeType ?ic Auxiliary)
       (equivalent (associative restructuring) ?il)
       (hasKnowledgeType ?hc Auxiliary)
       (equivalent (any accretion) ?hl)
       ;; get fund competency
       (getElement ?e ((class CurrentLDElement)))
       (getPropertyValue ?c ?e hasFundCompetency)
       (getCurrentLearningResourceType ?types)
       ;; get goals
       (getLearnerPropertyQuery ?tmpq2 ?c ?holders)
       (getPropertyValue ?sl ?hl hasSkillLevel)
       (getLevel ?hlslk2 (?sl tuning))
       (buildPropertyQuery ?q2 hasLearningResourceType ?types
                           ((class Auxiliary)
                            (property hasLearningObjective ?c ?hlslk2) . ?tmpq2))
       (getOrBuildReadyAux ?hauxslk2 ?q2 ?holders)
       (getGoalFromAuxiliary ?hgoalslk2 ?hauxslk2 ?c ?hlslk2))
      ((createLDAnchoredInstructionPhase ((?ic ?il) (?hc ?hl)) (?instructors ?holders))
       (createLDAnchoredInstructionPhase ((?ic ?il) ?hgoalslk2) (?instructors ?holders))))
   
   ;; fall-back
   (:method (createAnchoredInstructionCLScenario ?goals ?groups)
      ()
      ((!!addInWorldState (createAnchoredInstruction fall-back ?goals ?groups))))
   
